version: '3'
services:
  backend:
    image: dnridwn/chat-with-gemini-backend
    platform: linux/amd64
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
  frontend:
    image: dnridwn/chat-with-gemini-frontend
    platform: linux/amd64
    build:
      context: ./frontend
    ports:
      - "80:80"